# Generated by Django 4.2.3 on 2023-07-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0004_rename_banco_account_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('payment_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.category')),
            ],
        ),
    ]
