# Generated by Django 4.2.3 on 2023-07-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_banco_account_bank'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill_paid',
            new_name='BillPaid',
        ),
    ]
