# Generated by Django 4.2.3 on 2023-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_rename_bill_paid_billpaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payment_date',
            new_name='due_date',
        ),
    ]
