# Generated by Django 4.2.3 on 2023-07-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_rename_payment_date_bill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaid',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.bill'),
        ),
    ]
