# Generated by Django 4.2.3 on 2023-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('banco', models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('BR', 'Bradesco'), ('SAN', 'Santander')], max_length=3)),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('value', models.FloatField()),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
    ]
