# Generated by Django 4.2.3 on 2023-07-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_categoy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='banco',
            new_name='bank',
        ),
    ]
