# Generated by Django 4.2.3 on 2023-07-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0004_rename_banco_account_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('I', 'Input'), ('O', 'Output')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.category')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.account')),
            ],
        ),
    ]
