# Generated by Django 4.2.3 on 2023-07-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_banco_account_bank'),
        ('bank_statement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values',
            new_name='BankStatement',
        ),
    ]
