# Generated by Django 4.2.3 on 2023-07-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0002_rename_values_bankstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='conta',
            new_name='account',
        ),
    ]
