# Generated by Django 4.2.3 on 2023-07-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0003_rename_conta_bankstatement_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(),
        ),
    ]
